export const themes = [
    {
        id: 'liquid-green',
        name: 'Liquid Green',
        category: 'Vibrant',
        background: 'url("https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=2070&auto=format&fit=crop")',
        buttonStyle: 'bg-[#b6ff00] text-black border border-transparent hover:scale-105 transition-transform',
        textStyle: 'text-black',
        brandingColor: 'text-[#b6ff00]',
        handleFont: 'font-serif italic font-black text-3xl tracking-tight text-[#b6ff00] drop-shadow-[0_2px_4px_rgba(0,0,0,0.4)]',
        cardBackground: 'bg-white/90 backdrop-blur-md text-black font-semibold',
        brandingBubbleStyle: 'bg-black/20 backdrop-blur-md border border-white/10',
        coverImage: 'bg-gradient-to-br from-[#b6ff00] via-[#88cc00] to-[#00d2ff]',
        tile1Bg: 'bg-[#b6ff00]', tile2Bg: 'bg-white', tile3Bg: 'bg-[#88cc00]', tile4Bg: 'bg-[#00d2ff]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-[#b6ff00] hover:text-black transition-colors',
        chatBubbleAIStyle: 'bg-white/90 backdrop-blur-md text-black border border-black/5 rounded-2xl rounded-bl-sm shadow-md',
        chatBubbleUserStyle: 'bg-[#b6ff00] text-black rounded-2xl rounded-br-sm shadow-lg border border-black/5 px-4 py-2',
        chatInputStyle: 'bg-white/80 text-black border border-black/10 rounded-full focus:outline-none focus:ring-1 focus:ring-black/20 placeholder-black/40 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/95 via-white/80 to-transparent',
        previewBg: '#064e3b'
    },
    {
        id: 'clean-white',
        name: 'Clean White',
        category: 'Minimal',
        background: '#f4f4f5',
        buttonStyle: 'bg-white text-black border border-gray-200 shadow-sm hover:bg-gray-50 transition-colors',
        textStyle: 'text-black',
        brandingColor: 'text-black',
        handleFont: 'font-sans font-black tracking-tighter uppercase',
        cardBackground: 'bg-white text-black font-semibold shadow-sm',
        brandingBubbleStyle: 'bg-white shadow-sm border border-black/5',
        coverImage: 'bg-gradient-to-br from-[#f8fafc] to-[#e2e8f0]',
        tile1Bg: 'bg-white', tile2Bg: 'bg-[#f8fafc]', tile3Bg: 'bg-[#e2e8f0]', tile4Bg: 'bg-black',
        socialIconStyle: 'bg-black/5 text-black border border-black/5 hover:bg-black hover:text-white transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black text-white rounded-2xl rounded-br-sm shadow-lg border border-black/5',
        chatInputStyle: 'bg-white/80 text-black border border-black/10 rounded-full focus:outline-none focus:ring-1 focus:ring-black/20 placeholder-black/40 backdrop-blur-md shadow-inner',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/95 via-white/80 to-transparent',
        previewBg: '#e2e8f0'
    },
    {
        id: 'dark-3d-star',
        name: 'Dark 3D Star',
        category: 'Dark',
        background: 'linear-gradient(to bottom, #181816, #20201c)',
        buttonStyle: 'bg-white/20 text-white backdrop-blur-md border border-white/10 hover:bg-white/30 transition-colors shadow-[0_4px_30px_rgba(0,0,0,0.1)]',
        textStyle: 'text-white',
        brandingColor: 'text-white',
        handleFont: 'font-sans font-black tracking-tighter uppercase',
        cardBackground: 'bg-white/10 backdrop-blur-md text-white font-semibold border border-white/10',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-white/10',
        coverImage: 'bg-gradient-to-br from-[#1a1a1a] to-[#333333]',
        tile1Bg: 'bg-[#1a1a1a]', tile2Bg: 'bg-[#333333]', tile3Bg: 'bg-white/10', tile4Bg: 'bg-black',
        socialIconStyle: 'bg-white/5 text-white border border-white/10 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white text-black rounded-2xl rounded-br-sm shadow-xl border border-white/10 px-4 py-2',
        chatInputStyle: 'bg-white/10 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/30 backdrop-blur-xl',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/95 via-black/80 to-transparent',
        previewBg: '#0f172a'
    },
    {
        id: 'light-cloth',
        name: 'Light Cloth',
        category: 'Organic',
        background: 'url("https://images.unsplash.com/photo-1601243765103-68d27fd11c34?q=80&w=1956&auto=format&fit=crop")',
        buttonStyle: 'bg-black/5 text-black border border-black/10 hover:bg-black/10 transition-colors backdrop-blur-sm',
        textStyle: 'text-[#333333]',
        brandingColor: 'text-[#333333]',
        handleFont: 'font-serif italic font-black text-2xl tracking-tight',
        cardBackground: 'bg-white/80 backdrop-blur-sm text-[#333] font-semibold shadow-sm border border-black/5',
        brandingBubbleStyle: 'bg-black/5 backdrop-blur-sm border border-black/10',
        coverImage: 'bg-gradient-to-br from-[#e5e5e5] to-[#d4d4d4]',
        tile1Bg: 'bg-[#e5e5e5]', tile2Bg: 'bg-[#d4d4d4]', tile3Bg: 'bg-[#f5f5f5]', tile4Bg: 'bg-[#333333]',
        socialIconStyle: 'bg-black/5 text-[#333] border border-black/5 hover:bg-black hover:text-white transition-colors',
        chatBubbleAIStyle: 'bg-white/95 backdrop-blur-md text-black border border-black/5 rounded-2xl rounded-bl-sm shadow-md',
        chatBubbleUserStyle: 'bg-white/60 backdrop-blur-md text-[#333333] rounded-2xl rounded-br-sm shadow-sm border border-black/10 px-4 py-2',
        chatInputStyle: 'bg-white/80 text-black border border-black/10 rounded-full focus:outline-none focus:ring-1 focus:ring-black/20 placeholder-black/30 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/95 via-white/80 to-transparent',
        previewBg: '#d6d3d1'
    },
    {
        id: 'bw-contrast',
        name: 'B&W Contrast',
        category: 'Monochrome',
        background: 'linear-gradient(to bottom, #d4d4d4, #e5e5e5)',
        buttonStyle: 'bg-white/50 text-black border-2 border-black backdrop-blur-md hover:bg-white/70 transition-colors',
        textStyle: 'text-black',
        brandingColor: 'text-white',
        handleFont: 'font-serif italic font-black text-4xl tracking-tighter text-black',
        cardBackground: 'bg-black text-white font-black uppercase tracking-tight',
        brandingBubbleStyle: 'bg-black border-2 border-black shadow-[2px_2px_0_white]',
        coverImage: 'bg-gradient-to-br from-[#000000] to-[#444444]',
        tile1Bg: 'bg-black', tile2Bg: 'bg-white', tile3Bg: 'bg-[#444444]', tile4Bg: 'bg-[#888888]',
        socialIconStyle: 'bg-white text-black border-2 border-black hover:bg-black hover:text-white transition-colors',
        chatBubbleAIStyle: 'bg-white backdrop-blur-none text-black border-2 border-black rounded-2xl rounded-bl-sm shadow-[4px_4px_0_black]',
        chatBubbleUserStyle: 'bg-black text-white rounded-2xl rounded-br-sm shadow-lg px-4 py-2',
        chatInputStyle: 'bg-white text-black border-2 border-black rounded-full focus:outline-none placeholder-black/40',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#d4d4d4] via-[#d4d4d4]/80 to-transparent',
        previewBg: '#334155'
    },
    {
        id: 'minimal-light',
        name: 'Minimal Light',
        category: 'Minimal',
        background: '#FFFFFF',
        buttonStyle: 'bg-black text-white',
        textStyle: 'text-black',
        brandingColor: 'text-black',
        handleFont: 'font-sans font-black tracking-tighter uppercase text-2xl',
        cardBackground: 'bg-white border border-black/5 shadow-sm font-bold text-xs tracking-widest uppercase',
        brandingBubbleStyle: 'bg-white shadow-md border border-black/5',
        coverImage: 'bg-gradient-to-br from-[#ffffff] to-[#f1f5f9]',
        tile1Bg: 'bg-white', tile2Bg: 'bg-[#f1f5f9]', tile3Bg: 'bg-[#e2e8f0]', tile4Bg: 'bg-black',
        socialIconStyle: 'bg-black/5 text-black border border-black/5 hover:bg-black hover:text-white transition-colors',
        chatBubbleAIStyle: 'bg-gray-50 text-black border border-black/5 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black text-white rounded-2xl rounded-br-sm shadow-xl px-4 py-2',
        chatInputStyle: 'bg-gray-50 text-black border border-black/10 rounded-full focus:outline-none placeholder-gray-400',
        chatInputContainerStyle: 'bg-gradient-to-t from-white via-white/80 to-transparent',
        previewBg: '#f1f5f9'
    },
    {
        id: 'minimal-dark',
        name: 'Minimal Dark',
        category: 'Minimal',
        background: '#000000',
        buttonStyle: 'bg-white text-black',
        textStyle: 'text-white',
        brandingColor: 'text-white',
        handleFont: 'font-sans font-black tracking-tighter uppercase text-2xl',
        cardBackground: 'bg-white text-black font-black uppercase text-xs tracking-widest',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-white/10',
        coverImage: 'bg-gradient-to-br from-[#0a0a0a] to-[#262626]',
        tile1Bg: 'bg-[#0a0a0a]', tile2Bg: 'bg-[#262626]', tile3Bg: 'bg-white', tile4Bg: 'bg-black',
        socialIconStyle: 'bg-white/10 text-white border border-white/10 hover:bg-white hover:text-black transition-colors',
        chatBubbleAIStyle: 'bg-[#1a1a1a] text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-lg',
        chatBubbleUserStyle: 'bg-white text-black rounded-2xl rounded-br-sm shadow-xl px-4 py-2',
        chatInputStyle: 'bg-white/5 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/30 placeholder-white/30 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black via-black/80 to-transparent',
        previewBg: '#020617'
    },
    {
        id: 'soft-sand',
        name: 'Soft Sand',
        category: 'Minimal',
        background: '#F5F5DC',
        buttonStyle: 'bg-[#8B4513] text-white',
        textStyle: 'text-[#5C4033]',
        brandingColor: 'text-[#8B4513]',
        handleFont: 'font-sans font-medium',
        cardBackground: 'bg-white text-black',
        brandingBubbleStyle: 'bg-white/50 backdrop-blur-md border border-[#8B4513]/10',
        coverImage: 'bg-gradient-to-br from-[#f5f5dc] to-[#d2b48c]',
        tile1Bg: 'bg-[#f5f5dc]', tile2Bg: 'bg-[#d2b48c]', tile3Bg: 'bg-[#8B4513]', tile4Bg: 'bg-white',
        socialIconStyle: 'bg-black/5 text-[#5C4033] border border-black/5 hover:bg-[#8B4513] hover:text-white transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent',
        previewBg: '#e7e5e4'
    },
    {
        id: 'slate-grey',
        name: 'Slate Grey',
        category: 'Minimal',
        background: '#708090',
        buttonStyle: 'bg-white text-[#708090]',
        textStyle: 'text-white',
        brandingColor: 'text-white',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-white/20',
        handleFont: 'font-sans font-black tracking-tighter uppercase text-3xl',
        cardBackground: 'bg-white text-[#708090] font-bold',
        tile1Bg: 'bg-[#708090]', tile2Bg: 'bg-[#94a3b8]', tile3Bg: 'bg-[#475569]', tile4Bg: 'bg-[#1e293b]',
        coverImage: 'bg-gradient-to-br from-[#708090] to-[#1e293b]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/20 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white text-[#708090] rounded-2xl rounded-br-sm shadow-xl px-4 py-2',
        chatInputStyle: 'bg-white/10 text-white border border-white/20 rounded-full focus:outline-none placeholder-white/40 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#708090] via-[#708090]/80 to-transparent',
        previewBg: '#334155'
    },
    {
        id: 'pebble',
        name: 'Pebble',
        category: 'Minimal',
        background: '#E0E0E0',
        buttonStyle: 'bg-black text-white',
        textStyle: 'text-gray-800',
        brandingColor: 'text-black',
        brandingBubbleStyle: 'bg-white shadow-sm border border-black/10',
        handleFont: 'font-sans font-black tracking-tighter uppercase text-2xl',
        cardBackground: 'bg-white text-black font-bold border border-black/5',
        tile1Bg: 'bg-[#E0E0E0]', tile2Bg: 'bg-[#BDBDBD]', tile3Bg: 'bg-[#9E9E9E]', tile4Bg: 'bg-[#757575]',
        coverImage: 'bg-gradient-to-br from-[#E0E0E0] to-[#9E9E9E]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white text-black border border-black/5 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black text-white rounded-2xl rounded-br-sm shadow-xl px-4 py-2',
        chatInputStyle: 'bg-white text-black border border-black/10 rounded-full focus:outline-none placeholder-gray-400',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#E0E0E0] via-[#E0E0E0]/80 to-transparent',
        previewBg: '#94a3b8'
    },
    {
        id: 'sunset-glow',
        name: 'Sunset Glow',
        category: 'Gradient',
        background: 'linear-gradient(135deg, #FF7E5F, #FEB47B)',
        buttonStyle: 'bg-white/20 text-white backdrop-blur-sm border border-white/30',
        textStyle: 'text-white',
        brandingColor: 'text-white',
        brandingBubbleStyle: 'bg-white/20 backdrop-blur-md border border-white/30',
        handleFont: 'font-sans font-black tracking-tighter uppercase text-3xl',
        cardBackground: 'bg-white/20 backdrop-blur-md text-white border border-white/20 font-bold',
        tile1Bg: 'bg-[#FF7E5F]', tile2Bg: 'bg-[#FEB47B]', tile3Bg: 'bg-[#FF9966]', tile4Bg: 'bg-[#FF5E62]',
        coverImage: 'bg-gradient-to-br from-[#FF7E5F] to-[#FEB47B]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/20 backdrop-blur-xl text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white text-[#FF7E5F] rounded-2xl rounded-br-sm shadow-xl px-4 py-2',
        chatInputStyle: 'bg-white/10 text-white border border-white/30 rounded-full focus:outline-none placeholder-white/60 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#FF7E5F] via-[#FF7E5F]/80 to-transparent',
        previewBg: '#7c2d12'
    },
    {
        id: 'ocean-breeze',
        name: 'Ocean Breeze',
        category: 'Gradient',
        background: 'linear-gradient(135deg, #00C9FF, #92FE9D)',
        buttonStyle: 'bg-white text-[#00C9FF] shadow-lg',
        textStyle: 'text-white',
        brandingColor: 'text-white',
        brandingBubbleStyle: 'bg-white/20 backdrop-blur-md border border-white/30',
        handleFont: 'font-sans font-black tracking-tighter uppercase text-3xl',
        cardBackground: 'bg-white/20 backdrop-blur-md text-white border border-white/20 font-bold',
        tile1Bg: 'bg-[#00C9FF]', tile2Bg: 'bg-[#92FE9D]', tile3Bg: 'bg-[#00d2ff]', tile4Bg: 'bg-[#3a7bd5]',
        coverImage: 'bg-gradient-to-br from-[#00C9FF] to-[#92FE9D]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/20 backdrop-blur-xl text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white text-[#00C9FF] rounded-2xl rounded-br-sm shadow-xl px-4 py-2',
        chatInputStyle: 'bg-white/10 text-white border border-white/20 rounded-full focus:outline-none placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#00C9FF] via-[#00C9FF]/80 to-transparent',
        previewBg: '#065f46'
    },
    {
        id: 'midnight-purple',
        name: 'Midnight Purple',
        category: 'Gradient',
        background: 'linear-gradient(135deg, #4A00E0, #8E2DE2)',
        buttonStyle: 'bg-transparent text-white border-2 border-white',
        textStyle: 'text-white',
        brandingColor: 'text-white',
        brandingBubbleStyle: 'bg-white/20 backdrop-blur-md border border-white/30',
        handleFont: 'font-sans font-black tracking-tighter uppercase text-3xl',
        cardBackground: 'bg-white/10 backdrop-blur-md text-white border border-white/20 font-bold',
        tile1Bg: 'bg-[#4A00E0]', tile2Bg: 'bg-[#8E2DE2]', tile3Bg: 'bg-[#6a11cb]', tile4Bg: 'bg-[#2575fc]',
        coverImage: 'bg-gradient-to-br from-[#4A00E0] to-[#8E2DE2]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/40 backdrop-blur-xl text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-[#8E2DE2] text-white rounded-2xl rounded-br-sm shadow-xl px-4 py-2 border border-white/20',
        chatInputStyle: 'bg-white/5 text-white border border-white/20 rounded-full focus:outline-none placeholder-white/40 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#4A00E0] via-[#4A00E0]/80 to-transparent',
        previewBg: '#2e1065'
    },
    {
        id: 'cherry-blossom',
        name: 'Cherry Blossom',
        category: 'Gradient',
        background: 'linear-gradient(135deg, #FF9A9E, #FECFEF)',
        buttonStyle: 'bg-white/50 text-[#D84380] backdrop-blur-md',
        textStyle: 'text-[#D84380]',
        brandingColor: 'text-[#D84380]',
        brandingBubbleStyle: 'bg-white/40 backdrop-blur-md border border-[#D84380]/10',
        handleFont: 'font-serif font-black italic text-3xl tracking-tight text-[#D84380]',
        cardBackground: 'bg-white/40 backdrop-blur-md text-[#D84380] border border-[#D84380]/20 font-bold',
        tile1Bg: 'bg-[#FF9A9E]', tile2Bg: 'bg-[#FECFEF]', tile3Bg: 'bg-[#FFD1DC]', tile4Bg: 'bg-[#FFB7B2]',
        coverImage: 'bg-gradient-to-br from-[#FF9A9E] to-[#FECFEF]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/60 backdrop-blur-md text-[#D84380] border border-[#D84380]/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-[#D84380] text-white rounded-2xl rounded-br-sm shadow-xl px-4 py-2 border border-white/10',
        chatInputStyle: 'bg-white/60 text-[#D84380] border border-[#D84380]/20 rounded-full focus:outline-none placeholder-[#D84380]/40 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#FF9A9E] via-[#FF9A9E]/80 to-transparent',
        previewBg: '#9d174d'
    },
    {
        id: 'neon-city',
        name: 'Neon City',
        category: 'Gradient',
        background: 'linear-gradient(135deg, #0F2027, #203A43, #2C5364)',
        buttonStyle: 'bg-[#00FF87] text-black font-bold border border-[#60EFFF] shadow-[0_0_15px_rgba(0,255,135,0.5)]',
        textStyle: 'text-white',
        brandingColor: 'text-[#00FF87]',
        brandingBubbleStyle: 'bg-black/40 backdrop-blur-md border border-[#00FF87]/20',
        handleFont: 'font-mono font-black uppercase tracking-[0.3em] text-[#00FF87] drop-shadow-[0_0_8px_rgba(0,255,135,0.8)]',
        cardBackground: 'bg-black/40 backdrop-blur-md text-[#00FF87] border border-[#00FF87]/30',
        tile1Bg: 'bg-[#0F2027]', tile2Bg: 'bg-[#203A43]', tile3Bg: 'bg-[#2C5364]', tile4Bg: 'bg-black',
        coverImage: 'bg-gradient-to-br from-[#00FF87] to-[#60EFFF]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-[#00FF87] text-black rounded-2xl rounded-br-sm shadow-[0_0_15px_rgba(0,255,135,0.4)]',
        chatInputStyle: 'bg-black/40 text-white border border-[#00FF87]/30 rounded-full focus:outline-none focus:ring-1 focus:ring-[#00FF87]/50 placeholder-white/30 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/95 via-black/80 to-transparent',
        previewBg: '#020617'
    },
    {
        id: 'cyber-punk',
        name: 'Cyberpunk',
        category: 'Y2K',
        background: '#0D0E15',
        buttonStyle: 'bg-transparent text-[#FCEE0A] border-2 border-[#FCEE0A] shadow-[4px_4px_0_#FCEE0A] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all',
        textStyle: 'text-[#00FFFF]',
        brandingColor: 'text-[#FCEE0A]',
        brandingBubbleStyle: 'bg-[#FF003C]/20 backdrop-blur-md border border-[#FCEE0A]/30',
        handleFont: 'font-mono font-black italic uppercase tracking-tighter text-[#FCEE0A] drop-shadow-[2px_2px_0_#FF003C]',
        cardBackground: 'bg-[#FCEE0A] text-black uppercase font-black',
        tile1Bg: 'bg-[#FF003C]', tile2Bg: 'bg-[#00FFFF]', tile3Bg: 'bg-[#FCEE0A]', tile4Bg: 'bg-black',
        coverImage: 'bg-gradient-to-br from-[#FCEE0A] via-[#FF003C] to-[#00FFFF]',
        socialIconStyle: 'bg-[#FF003C] text-white hover:bg-[#FF003C]/80 transition-colors',
        chatBubbleAIStyle: 'bg-[#1a1a1a] text-[#00FFFF] border border-[#00FFFF]/30 rounded-2xl rounded-bl-sm shadow-[0_0_10px_rgba(0,255,255,0.2)]',
        chatBubbleUserStyle: 'bg-[#FCEE0A] text-black rounded-2xl rounded-br-sm shadow-[4px_4px_0_#FF003C] px-4 py-2',
        chatInputStyle: 'bg-black text-[#00FFFF] border-2 border-[#FCEE0A] rounded-none focus:outline-none placeholder-[#00FFFF]/30',
        chatInputContainerStyle: 'bg-black/90 border-t-4 border-[#FCEE0A]',
        previewBg: '#000000'
    },
    {
        id: 'vaporwave',
        name: 'Vaporwave',
        category: 'Y2K',
        background: 'linear-gradient(180deg, #FF71CE, #01CDFE)',
        buttonStyle: 'bg-[#B967FF] text-white border-2 border-white font-bold',
        textStyle: 'text-white text-shadow-sm',
        brandingColor: 'text-white',
        brandingBubbleStyle: 'bg-white/20 backdrop-blur-md border-2 border-white',
        handleFont: 'font-serif italic font-black text-4xl tracking-tighter uppercase text-white drop-shadow-[2px_2px_0_#01CDFE]',
        cardBackground: 'bg-white text-[#FF71CE] font-black italic shadow-[4px_4px_0_#01CDFE]',
        tile1Bg: 'bg-[#FF71CE]', tile2Bg: 'bg-[#01CDFE]', tile3Bg: 'bg-[#B967FF]', tile4Bg: 'bg-[#FFF200]',
        coverImage: 'bg-gradient-to-br from-[#FF71CE] via-[#B967FF] to-[#01CDFE]',
        socialIconStyle: 'bg-[#01CDFE] text-white border-2 border-white hover:bg-[#01CDFE]/80 transition-colors',
        chatBubbleAIStyle: 'bg-white/20 backdrop-blur-xl text-white border-2 border-white rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-[#FF71CE] text-white rounded-2xl rounded-br-sm shadow-[4px_4px_0_#B967FF] italic px-4 py-2 border-2 border-white',
        chatInputStyle: 'bg-white/10 text-white border-2 border-white rounded-full focus:outline-none placeholder-white/60 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#01CDFE] via-[#01CDFE]/80 to-transparent',
        previewBg: '#4a148c'
    },
    {
        id: 'brutalism',
        name: 'Brutalism',
        category: 'Aesthetic',
        background: '#D6D6D6',
        buttonStyle: 'bg-black text-white border-4 border-black font-black uppercase hover:bg-white hover:text-black transition-colors',
        textStyle: 'text-black',
        brandingColor: 'text-black',
        brandingBubbleStyle: 'bg-white border-4 border-black shadow-[4px_4px_0_black]',
        handleFont: 'font-sans font-black uppercase text-4xl tracking-tighter leading-none',
        cardBackground: 'bg-white text-black uppercase font-black border-4 border-black shadow-[8px_8px_0_black]',
        tile1Bg: 'bg-[#ff003c]', tile2Bg: 'bg-[#00ffff]', tile3Bg: 'bg-[#fcee0a]', tile4Bg: 'bg-white',
        coverImage: 'bg-gradient-to-br from-[#D6D6D6] to-[#000000]',
        socialIconStyle: 'bg-black text-white border-2 border-black hover:bg-white hover:text-black transition-colors',
        chatBubbleAIStyle: 'bg-white text-black border-4 border-black rounded-2xl rounded-bl-sm shadow-[4px_4px_0_black]',
        chatBubbleUserStyle: 'bg-yellow-400 text-black rounded-2xl rounded-br-sm border-4 border-black shadow-[4px_4px_0_black] px-4 py-2',
        chatInputStyle: 'bg-white text-black border-4 border-black rounded-full focus:outline-none placeholder-black/50',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#D6D6D6] via-[#D6D6D6]/80 to-transparent',
        previewBg: '#171717'
    },
    {
        id: 'glassmorphism',
        name: 'Glassmorphism',
        category: 'Aesthetic',
        background: 'linear-gradient(45deg, #12c2e9, #c471ed, #f64f59)',
        buttonStyle: 'bg-white/10 text-white backdrop-blur-xl border border-white/20 shadow-[0_8px_32px_0_rgba(31,38,135,0.37)]',
        textStyle: 'text-white',
        brandingColor: 'text-white',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-xl border border-white/20',
        handleFont: 'font-sans font-thin tracking-[0.2em] uppercase text-2xl',
        cardBackground: 'bg-white/10 backdrop-blur-2xl text-white border border-white/20 shadow-xl',
        tile1Bg: 'bg-white/10', tile2Bg: 'bg-white/20', tile3Bg: 'bg-white/5', tile4Bg: 'bg-white/15',
        coverImage: 'bg-gradient-to-br from-[#12c2e9] via-[#c471ed] to-[#f64f59]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/10 backdrop-blur-xl text-white border border-white/20 rounded-2xl rounded-bl-sm shadow-lg',
        chatBubbleUserStyle: 'bg-white/30 backdrop-blur-2xl text-white rounded-2xl rounded-br-sm shadow-2xl border border-white/30 font-medium px-4 py-2',
        chatInputStyle: 'bg-white/10 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/40 placeholder-white/40 backdrop-blur-xl transition-all',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/20 via-black/10 to-transparent',
        previewBg: '#1e1b4b'
    },
    {
        id: 'pastel-dreams',
        name: 'Pastel Dreams',
        category: 'Aesthetic',
        background: '#FDF6E3',
        buttonStyle: 'bg-[#FFB7B2] text-white shadow-sm',
        textStyle: 'text-[#4A4947]',
        brandingColor: 'text-[#D47672]',
        brandingBubbleStyle: 'bg-white shadow-sm border border-[#FFB7B2]/10',
        handleFont: 'font-serif italic font-black text-3xl tracking-tight text-[#D47672] drop-shadow-sm',
        cardBackground: 'bg-white text-[#4A4947] font-bold border border-black/5',
        tile1Bg: 'bg-[#FFB7B2]', tile2Bg: 'bg-[#FFD1DC]', tile3Bg: 'bg-[#B2E2F2]', tile4Bg: 'bg-[#E2F2B2]',
        coverImage: 'bg-gradient-to-br from-[#FFB7B2] via-[#FFD1DC] to-[#B2E2F2]',
        socialIconStyle: 'bg-white text-[#4A4947] border border-black/5 hover:bg-[#FFB7B2] hover:text-white transition-all',
        chatBubbleAIStyle: 'bg-white text-[#4A4947] border border-black/5 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-[#FFB7B2] text-white rounded-2xl rounded-br-sm shadow-md px-4 py-2 border border-white/10',
        chatInputStyle: 'bg-white text-[#4A4947] border border-black/10 rounded-full focus:outline-none placeholder-gray-400',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#FDF6E3] via-[#FDF6E3]/95 to-transparent',
        previewBg: '#fef3c7'
    },
    {
        id: 'forest',
        name: 'Forest',
        category: 'Organic',
        background: '#2C4C3B',
        buttonStyle: 'bg-[#E8F1E9] text-[#2C4C3B]',
        textStyle: 'text-[#E8F1E9]',
        brandingColor: 'text-[#E8F1E9]',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-white/10',
        handleFont: 'font-serif font-black italic text-3xl tracking-tight',
        cardBackground: 'bg-[#E8F1E9] text-[#2C4C3B] font-bold',
        tile1Bg: 'bg-[#2C4C3B]', tile2Bg: 'bg-[#3D6B52]', tile3Bg: 'bg-[#4E8A69]', tile4Bg: 'bg-[#1A2E24]',
        coverImage: 'bg-gradient-to-br from-[#2C4C3B] to-[#E8F1E9]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/10 backdrop-blur-md text-[#E8F1E9] border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-[#E8F1E9] text-[#2C4C3B] rounded-2xl rounded-br-sm shadow-xl px-4 py-2',
        chatInputStyle: 'bg-white/5 text-[#E8F1E9] border border-white/10 rounded-full focus:outline-none placeholder-[#E8F1E9]/40 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#2C4C3B] via-[#2C4C3B]/80 to-transparent',
        previewBg: '#064e3b'
    },
    {
        id: 'clay',
        name: 'Clay',
        category: 'Organic',
        background: '#C49A7E',
        buttonStyle: 'bg-[#5C4033] text-white',
        textStyle: 'text-[#3E2723]',
        brandingColor: 'text-[#5C4033]',
        brandingBubbleStyle: 'bg-white/20 backdrop-blur-md border border-[#5C4033]/10',
        handleFont: 'font-sans font-medium',
        cardBackground: 'bg-white text-[#5C4033]',
        tile1Bg: 'bg-[#C49A7E]', tile2Bg: 'bg-[#5C4033]', tile3Bg: 'bg-[#8B4513]', tile4Bg: 'bg-[#D2B48C]',
        coverImage: 'bg-gradient-to-br from-[#C49A7E] to-[#5C4033]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent',
        previewBg: '#451a03'
    },
    {
        id: 'sage',
        name: 'Sage',
        category: 'Organic',
        background: '#8A9A86',
        buttonStyle: 'bg-white/30 text-white backdrop-blur-sm border border-white/40',
        textStyle: 'text-white',
        brandingColor: 'text-white',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-white/10',
        handleFont: 'font-sans font-light',
        cardBackground: 'bg-white text-[#8A9A86]',
        tile1Bg: 'bg-[#8A9A86]', tile2Bg: 'bg-[#4B5348]', tile3Bg: 'bg-[#6B7868]', tile4Bg: 'bg-[#A8B5A5]',
        coverImage: 'bg-gradient-to-br from-[#8A9A86] to-[#4B5348]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent',
        previewBg: '#365314'
    },
    {
        id: 'desert',
        name: 'Desert',
        category: 'Organic',
        background: '#E0B589',
        buttonStyle: 'bg-[#9A6A4E] text-white shadow-md',
        textStyle: 'text-[#5E3A25]',
        brandingColor: 'text-[#9A6A4E]',
        brandingBubbleStyle: 'bg-white/20 border border-[#9A6A4E]/20',
        handleFont: 'font-serif font-bold uppercase',
        cardBackground: 'bg-[#9A6A4E] text-white',
        tile1Bg: 'bg-[#E0B589]', tile2Bg: 'bg-[#9A6A4E]', tile3Bg: 'bg-[#5E3A25]', tile4Bg: 'bg-[#C4A484]',
        coverImage: 'bg-gradient-to-br from-[#E0B589] to-[#9A6A4E]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent',
        previewBg: '#78350f'
    },
    {
        id: 'moss',
        name: 'Moss',
        category: 'Organic',
        background: '#596C56',
        buttonStyle: 'bg-transparent text-[#D4DFD2] border border-[#D4DFD2]',
        textStyle: 'text-[#D4DFD2]',
        brandingColor: 'text-[#D4DFD2]',
        brandingBubbleStyle: 'bg-white/5 backdrop-blur-sm border border-[#D4DFD2]/10',
        handleFont: 'font-sans font-medium',
        cardBackground: 'bg-[#D4DFD2] text-[#596C56]',
        tile1Bg: 'bg-[#596C56]', tile2Bg: 'bg-[#D4DFD2]', tile3Bg: 'bg-[#849C81]', tile4Bg: 'bg-[#3E4C3C]',
        coverImage: 'bg-gradient-to-br from-[#596C56] to-[#D4DFD2]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent',
        previewBg: '#14532d'
    },
    {
        id: 'pop-art',
        name: 'Pop Art',
        category: 'Vibrant',
        background: '#FFD700',
        buttonStyle: 'bg-[#FF1493] text-white font-black border-4 border-black shadow-[4px_4px_0_black]',
        textStyle: 'text-black',
        brandingColor: 'text-[#FF1493]',
        handleFont: 'font-sans font-black uppercase text-4xl tracking-tighter text-black',
        cardBackground: 'bg-white text-black font-black border-4 border-black shadow-[6px_6px_0_black]',
        tile1Bg: 'bg-[#FF1493]', tile2Bg: 'bg-[#00BFFF]', tile3Bg: 'bg-[#32CD32]', tile4Bg: 'bg-white',
        brandingBubbleStyle: 'bg-white border-4 border-black shadow-[4px_4px_0_black]',
        coverImage: 'bg-gradient-to-br from-[#FFD700] via-[#FF1493] to-[#00BFFF]',
        socialIconStyle: 'bg-[#FF1493] text-white border-2 border-black hover:scale-110 transition-transform',
        chatBubbleAIStyle: 'bg-white text-black border-4 border-black rounded-2xl rounded-bl-sm',
        chatBubbleUserStyle: 'bg-[#FF1493] text-white rounded-2xl rounded-br-sm border-4 border-black shadow-[4px_4px_0_black] font-medium px-4 py-2',
        chatInputStyle: 'bg-white text-black border-4 border-black rounded-full focus:outline-none placeholder-black/40',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#FFD700] via-[#FFD700]/80 to-transparent',
        previewBg: '#000000'
    },
    {
        id: 'bubblegum',
        name: 'Bubblegum',
        category: 'Vibrant',
        background: '#FF69B4',
        buttonStyle: 'bg-white text-[#FF69B4] font-bold shadow-lg',
        textStyle: 'text-white',
        brandingColor: 'text-white',
        handleFont: 'font-sans font-black italic tracking-tighter text-3xl uppercase',
        cardBackground: 'bg-white text-[#FF69B4] font-black uppercase shadow-sm',
        tile1Bg: 'bg-[#FF69B4]', tile2Bg: 'bg-[#FFC0CB]', tile3Bg: 'bg-[#DB7093]', tile4Bg: 'bg-white',
        brandingBubbleStyle: 'bg-white/20 backdrop-blur-md border border-white/30',
        coverImage: 'bg-gradient-to-br from-[#FF69B4] via-[#FFC0CB] to-white',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/20 backdrop-blur-md text-white border border-white/30 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white text-[#FF69B4] rounded-2xl rounded-br-sm shadow-xl px-4 py-2',
        chatInputStyle: 'bg-white/10 text-white border border-white/30 rounded-full focus:outline-none placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#FF69B4] via-[#FF69B4]/80 to-transparent',
        previewBg: '#9d174d'
    },
    {
        id: 'citrus',
        name: 'Citrus',
        category: 'Vibrant',
        background: '#FF8C00',
        buttonStyle: 'bg-[#FFFF00] text-black font-bold',
        textStyle: 'text-white',
        brandingColor: 'text-[#FFFF00]',
        handleFont: 'font-sans font-black italic tracking-tighter uppercase text-4xl text-white drop-shadow-lg',
        cardBackground: 'bg-[#FFFF00] text-black font-black uppercase text-xs tracking-widest',
        tile1Bg: 'bg-[#FF8C00]', tile2Bg: 'bg-[#FFFF00]', tile3Bg: 'bg-white', tile4Bg: 'bg-[#FF4500]',
        brandingBubbleStyle: 'bg-white/20 backdrop-blur-md border border-white/30',
        coverImage: 'bg-gradient-to-br from-[#FF8C00] via-[#FFFF00] to-white',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/20 backdrop-blur-xl text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-[#FFFF00] text-black rounded-2xl rounded-br-sm shadow-xl px-4 py-2 border border-black/10',
        chatInputStyle: 'bg-white/10 text-white border border-white/20 rounded-full focus:outline-none placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#FF8C00] via-[#FF8C00]/80 to-transparent',
        previewBg: '#7c2d12'
    },
    {
        id: 'royal-blue',
        name: 'Royal',
        category: 'Vibrant',
        background: '#4169E1',
        buttonStyle: 'bg-[#FFD700] text-black font-bold shadow-[0_4px_14px_0_rgba(255,215,0,0.39)]',
        textStyle: 'text-white',
        brandingColor: 'text-[#FFD700]',
        handleFont: 'font-serif font-black italic text-4xl tracking-tight text-[#FFD700] drop-shadow-lg',
        cardBackground: 'bg-white text-[#4169E1] font-bold border border-[#4169E1]/10',
        tile1Bg: 'bg-[#4169E1]', tile2Bg: 'bg-[#FFD700]', tile3Bg: 'bg-white', tile4Bg: 'bg-[#000080]',
        brandingBubbleStyle: 'bg-white/20 backdrop-blur-md border border-white/30',
        coverImage: 'bg-gradient-to-br from-[#4169E1] via-[#FFD700] to-white',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/20 backdrop-blur-xl text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-[#FFD700] text-black rounded-2xl rounded-br-sm shadow-xl px-4 py-2 border border-black/10',
        chatInputStyle: 'bg-white/10 text-white border border-white/20 rounded-full focus:outline-none placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#4169E1] via-[#4169E1]/80 to-transparent',
        previewBg: '#1e3a8a'
    },
    {
        id: 'hyper-pink',
        name: 'Hyper Pink',
        category: 'Vibrant',
        background: '#FF007F',
        buttonStyle: 'bg-black text-white',
        textStyle: 'text-white',
        brandingColor: 'text-white',
        handleFont: 'font-mono font-black italic tracking-tighter text-4xl uppercase',
        cardBackground: 'bg-white text-black font-black uppercase text-[10px] tracking-[0.2em]',
        tile1Bg: 'bg-[#FF007F]', tile2Bg: 'bg-black', tile3Bg: 'bg-white', tile4Bg: 'bg-[#FF69B4]',
        brandingBubbleStyle: 'bg-black/20 backdrop-blur-md border border-white/10',
        coverImage: 'bg-gradient-to-br from-[#FF007F] to-black',
        socialIconStyle: 'bg-black text-white border border-white/20 hover:bg-gray-900 transition-colors',
        chatBubbleAIStyle: 'bg-white/10 backdrop-blur-md text-white border border-white/20 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black text-white rounded-2xl rounded-br-sm shadow-2xl tracking-widest px-4 py-2 border-2 border-white/10',
        chatInputStyle: 'bg-black text-white border-2 border-white/20 rounded-none focus:outline-none placeholder-white/30',
        chatInputContainerStyle: 'bg-[#FF007F] border-t-4 border-black',
        previewBg: '#000000'
    },
    {
        id: 'grid-paper',
        name: 'Grid Paper',
        category: 'Abstract',
        background: '#f0f0f0 radial-gradient(#d7d7d7 1px, transparent 1px)',
        backgroundSize: '20px 20px',
        buttonStyle: 'bg-white text-blue-600 border border-blue-600 font-mono',
        textStyle: 'text-blue-800',
        brandingColor: 'text-blue-600',
        handleFont: 'font-mono font-bold',
        cardBackground: 'bg-blue-600 text-white',
        tile1Bg: 'bg-[#f0f0f0]', tile2Bg: 'bg-blue-600', tile3Bg: 'bg-white', tile4Bg: 'bg-blue-800',
        brandingBubbleStyle: 'bg-white shadow-sm border border-black/10',
        coverImage: 'bg-gradient-to-br from-[#f0f0f0] to-[#d7d7d7]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent',
        previewBg: '#e2e8f0'
    },
    {
        id: 'dots',
        name: 'Polka Dots',
        category: 'Abstract',
        background: '#FFC0CB radial-gradient(#FF69B4 2px, transparent 2px)',
        backgroundSize: '15px 15px',
        buttonStyle: 'bg-white text-[#FF69B4] shadow-md',
        textStyle: 'text-[#C71585]',
        brandingColor: 'text-[#FF69B4]',
        handleFont: 'font-sans font-extrabold',
        cardBackground: 'bg-white text-[#C71585]',
        tile1Bg: 'bg-[#FFC0CB]', tile2Bg: 'bg-[#FF69B4]', tile3Bg: 'bg-white', tile4Bg: 'bg-[#C71585]',
        brandingBubbleStyle: 'bg-white shadow-sm border border-[#FF69B4]/10',
        coverImage: 'bg-gradient-to-br from-[#FFC0CB] to-[#FF69B4]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent',
        previewBg: '#fbcfe8'
    },
    {
        id: 'checkerboard',
        name: 'Checkerboard',
        category: 'Abstract',
        background: 'conic-gradient(from 90deg at 2px 2px,#0000 90deg,#fff 0) 0 0/20px 20px, #000',
        buttonStyle: 'bg-[#FFD700] text-black font-black uppercase border-2 border-black shadow-[4px_4px_0_black]',
        textStyle: 'text-white bg-black/50 px-4 py-1 rounded inline-block',
        brandingColor: 'text-[#FFD700]',
        handleFont: 'font-sans font-black uppercase text-3xl tracking-tighter text-white bg-black/80 px-4 py-1 border-2 border-white',
        cardBackground: 'bg-[#FFD700] text-black font-black uppercase border-2 border-black shadow-[4px_4px_0_black]',
        tile1Bg: 'bg-white', tile2Bg: 'bg-black', tile3Bg: 'bg-[#FFD700]', tile4Bg: 'bg-red-500',
        brandingBubbleStyle: 'bg-white border-2 border-black shadow-[4px_4px_0_black]',
        coverImage: 'bg-gradient-to-br from-white to-black',
        socialIconStyle: 'bg-white text-black border-2 border-black hover:bg-black hover:text-white transition-colors',
        chatBubbleAIStyle: 'bg-white text-black border-4 border-black rounded-none',
        chatBubbleUserStyle: 'bg-[#FFD700] text-black rounded-none border-4 border-black shadow-[4px_4px_0_black] px-4 py-2',
        chatInputStyle: 'bg-white text-black border-4 border-black rounded-none focus:outline-none placeholder-black/40',
        chatInputContainerStyle: 'bg-black border-t-4 border-white',
        previewBg: '#171717'
    },
    {
        id: 'waves',
        name: 'Waves',
        category: 'Abstract',
        background: 'repeating-radial-gradient( circle at 0 0, transparent 0, #4ca1af 10px ), repeating-linear-gradient( #2c3e50, #2c3e50 )',
        buttonStyle: 'bg-white/20 text-white backdrop-blur-md border border-white/30',
        textStyle: 'text-white',
        brandingColor: 'text-white',
        handleFont: 'font-serif font-black italic text-4xl tracking-tighter text-white drop-shadow-lg',
        cardBackground: 'bg-white/10 backdrop-blur-md text-white border border-white/20 font-bold',
        tile1Bg: 'bg-[#4ca1af]', tile2Bg: 'bg-[#2c3e50]', tile3Bg: 'bg-white/20', tile4Bg: 'bg-black/20',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-white/20',
        coverImage: 'bg-gradient-to-br from-[#4ca1af] to-[#2c3e50]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/40 backdrop-blur-xl text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white text-[#2c3e50] rounded-2xl rounded-br-sm shadow-xl px-4 py-2 border border-white/20',
        chatInputStyle: 'bg-white/10 text-white border border-white/20 rounded-full focus:outline-none placeholder-white/40 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#2c3e50] via-[#2c3e50]/80 to-transparent',
        previewBg: '#1e3a8a'
    },
    {
        id: 'stripes',
        name: 'Stripes',
        category: 'Abstract',
        background: 'repeating-linear-gradient( 45deg, #606dbc, #606dbc 10px, #465298 10px, #465298 20px )',
        buttonStyle: 'bg-white text-[#465298] shadow-lg font-bold',
        textStyle: 'text-white',
        brandingColor: 'text-white',
        handleFont: 'font-sans font-black tracking-tighter uppercase text-4xl text-white drop-shadow-lg',
        cardBackground: 'bg-white text-[#465298] font-bold border border-[#465298]/20',
        tile1Bg: 'bg-[#606dbc]', tile2Bg: 'bg-[#465298]', tile3Bg: 'bg-white', tile4Bg: 'bg-[#1a2e24]',
        brandingBubbleStyle: 'bg-white shadow-sm border border-[#465298]/10',
        coverImage: 'bg-gradient-to-br from-[#606dbc] to-[#465298]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/20 backdrop-blur-xl text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white text-[#465298] rounded-2xl rounded-br-sm shadow-xl px-4 py-2 border border-white/20',
        chatInputStyle: 'bg-white/10 text-white border border-white/20 rounded-full focus:outline-none placeholder-white/40 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#465298] via-[#465298]/80 to-transparent',
        previewBg: '#1e3a8a'
    },
    {
        id: 'obsidian',
        name: 'Obsidian',
        category: 'Dark',
        background: '#0B0C10',
        buttonStyle: 'bg-[#1F2833] text-[#66FCF1] border border-[#45A29E] hover:bg-[#45A29E] hover:text-black transition-colors',
        textStyle: 'text-[#C5C6C7]',
        brandingColor: 'text-[#66FCF1]',
        handleFont: 'font-mono font-bold text-[#66FCF1]',
        cardBackground: 'bg-[#66FCF1] text-black',
        tile1Bg: 'bg-[#1F2833]', tile2Bg: 'bg-[#66FCF1]', tile3Bg: 'bg-[#45A29E]', tile4Bg: 'bg-black',
        brandingBubbleStyle: 'bg-[#1F2833] border border-[#66FCF1]/20',
        coverImage: 'bg-gradient-to-br from-[#1F2833] to-[#0B0C10]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent',
        previewBg: '#020617'
    },
    {
        id: 'midnight',
        name: 'Midnight',
        category: 'Dark',
        background: '#121212',
        buttonStyle: 'bg-white/10 text-white border border-white/20 backdrop-blur-md',
        textStyle: 'text-gray-300',
        brandingColor: 'text-white',
        handleFont: 'font-sans font-black tracking-tighter uppercase text-3xl text-white drop-shadow-[0_0_10px_rgba(255,255,255,0.3)]',
        cardBackground: 'bg-white/5 backdrop-blur-md text-white border border-white/10 font-bold uppercase tracking-widest text-[10px]',
        tile1Bg: 'bg-[#121212]', tile2Bg: 'bg-[#1a1a1a]', tile3Bg: 'bg-white/10', tile4Bg: 'bg-black',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-white/10',
        coverImage: 'bg-gradient-to-br from-[#121212] via-[#333] to-black',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-[#1a1a1a] text-gray-300 border border-white/5 rounded-2xl rounded-bl-sm shadow-lg',
        chatBubbleUserStyle: 'bg-white text-black rounded-2xl rounded-br-sm shadow-2xl px-4 py-2',
        chatInputStyle: 'bg-white/5 text-white border border-white/10 rounded-full focus:outline-none placeholder-white/20 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black via-black/90 to-transparent',
        previewBg: '#000000'
    },
    {
        id: 'velvet',
        name: 'Velvet',
        category: 'Dark',
        background: '#350018',
        buttonStyle: 'bg-[#DEA5A4] text-[#350018] font-serif font-bold',
        textStyle: 'text-[#DEA5A4]',
        brandingColor: 'text-[#DEA5A4]',
        handleFont: 'font-serif italic text-3xl',
        cardBackground: 'bg-[#DEA5A4] text-[#350018]',
        tile1Bg: 'bg-[#350018]', tile2Bg: 'bg-[#DEA5A4]', tile3Bg: 'bg-[#5c0029]', tile4Bg: 'bg-[#8c003e]',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-[#DEA5A4]/20',
        coverImage: 'bg-gradient-to-br from-[#350018] to-[#DEA5A4]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent',
        previewBg: '#4c0519'
    },
    {
        id: 'emerald-city',
        name: 'Emerald City',
        category: 'Dark',
        background: '#023020',
        buttonStyle: 'bg-transparent text-[#50C878] border-2 border-[#50C878]',
        textStyle: 'text-[#50C878]',
        brandingColor: 'text-[#50C878]',
        handleFont: 'font-sans font-bold',
        cardBackground: 'bg-[#50C878] text-white',
        tile1Bg: 'bg-[#023020]', tile2Bg: 'bg-[#50C878]', tile3Bg: 'bg-[#045d3e]', tile4Bg: 'bg-[#067c52]',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-[#50C878]/20',
        coverImage: 'bg-gradient-to-br from-[#023020] to-[#50C878]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent',
        previewBg: '#064e3b'
    },
    {
        id: 'deep-space',
        name: 'Deep Space',
        category: 'Dark',
        background: 'radial-gradient(circle at center, #1B2735 0%, #090A0F 100%)',
        buttonStyle: 'bg-white/5 text-white backdrop-blur-xl border border-white/10 shadow-[0_0_15px_rgba(255,255,255,0.1)]',
        textStyle: 'text-gray-400',
        brandingColor: 'text-white',
        handleFont: 'font-mono font-black tracking-[0.4em] uppercase text-white drop-shadow-[0_0_12px_rgba(255,255,255,0.8)]',
        cardBackground: 'bg-black/60 backdrop-blur-2xl text-white border border-white/10 font-bold tracking-widest uppercase text-[10px]',
        tile1Bg: 'bg-[#1B2735]', tile2Bg: 'bg-[#090A0F]', tile3Bg: 'bg-white/5', tile4Bg: 'bg-black',
        brandingBubbleStyle: 'bg-white/5 backdrop-blur-xl border border-white/10',
        coverImage: 'bg-gradient-to-br from-[#1B2735] to-[#090A0F]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/5 backdrop-blur-2xl text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-lg',
        chatBubbleUserStyle: 'bg-white text-black rounded-2xl rounded-br-sm shadow-[0_0_20px_rgba(255,255,255,0.2)] px-4 py-2',
        chatInputStyle: 'bg-white/5 text-white border border-white/10 rounded-full focus:outline-none placeholder-white/20 backdrop-blur-xl',
        chatInputContainerStyle: 'bg-gradient-to-t from-black via-black/90 to-transparent',
        previewBg: '#020617'
    },
    {
        id: 'luna',
        name: 'Luna',
        category: 'Abstract',
        background: '#F0E6D2',
        buttonStyle: 'bg-[#3C3C3C] text-[#F0E6D2]',
        textStyle: 'text-[#3C3C3C]',
        brandingColor: 'text-[#3C3C3C]',
        handleFont: 'font-serif font-medium',
        cardBackground: 'bg-[#3C3C3C] text-white',
        tile1Bg: 'bg-[#F0E6D2]', tile2Bg: 'bg-[#3C3C3C]', tile3Bg: 'bg-white', tile4Bg: 'bg-[#d9cab3]',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-white/20',
        coverImage: 'bg-gradient-to-br from-[#F0E6D2] to-[#3C3C3C]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent',
        previewBg: '#d9cab3'
    },
    {
        id: 'mars',
        name: 'Mars',
        category: 'Abstract',
        background: '#AD3611',
        buttonStyle: 'bg-[#FF8C66] text-[#4A1607] font-bold',
        textStyle: 'text-[#FFD1BF]',
        brandingColor: 'text-[#FF8C66]',
        handleFont: 'font-sans font-black tracking-tighter uppercase text-4xl text-[#FF8C66] drop-shadow-lg',
        cardBackground: 'bg-white/10 backdrop-blur-md text-white border border-white/20 font-bold',
        tile1Bg: 'bg-[#AD3611]', tile2Bg: 'bg-[#FF8C66]', tile3Bg: 'bg-[#4A1607]', tile4Bg: 'bg-[#FFD1BF]',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-white/20',
        coverImage: 'bg-gradient-to-br from-[#AD3611] to-[#FF8C66]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-[#4A1607]/40 backdrop-blur-xl text-[#FFD1BF] border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-[#FF8C66] text-[#4A1607] rounded-2xl rounded-br-sm shadow-xl px-4 py-2 border border-white/20',
        chatInputStyle: 'bg-white/5 text-white border border-white/10 rounded-full focus:outline-none placeholder-white/30 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#AD3611] via-[#AD3611]/80 to-transparent',
        previewBg: '#4d1d0d'
    },
    {
        id: 'aurora',
        name: 'Aurora',
        category: 'Gradient',
        background: 'linear-gradient(to right, #00c6ff, #0072ff)',
        buttonStyle: 'bg-white/20 backdrop-blur-lg text-white border border-white/50 shadow-lg',
        textStyle: 'text-[#E0FFFF]',
        brandingColor: 'text-white',
        handleFont: 'font-sans font-black tracking-tighter uppercase text-4xl text-white drop-shadow-lg',
        cardBackground: 'bg-white/20 backdrop-blur-md text-white border border-white/30 font-bold',
        tile1Bg: 'bg-[#00c6ff]', tile2Bg: 'bg-[#0072ff]', tile3Bg: 'bg-white/20', tile4Bg: 'bg-black/20',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-white/20',
        coverImage: 'bg-gradient-to-br from-[#00c6ff] to-[#0072ff]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/20 backdrop-blur-xl text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white text-[#0072ff] rounded-2xl rounded-br-sm shadow-xl px-4 py-2',
        chatInputStyle: 'bg-white/10 text-white border border-white/30 rounded-full focus:outline-none placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#0072ff]/80 via-[#0072ff]/50 to-transparent',
        previewBg: '#1e3a8a'
    },
    {
        id: 'nebula',
        name: 'Nebula',
        category: 'Gradient',
        background: 'radial-gradient(circle, #662D8C 0%, #ED1E79 100%)',
        buttonStyle: 'bg-white text-[#662D8C] font-bold shadow-xl',
        textStyle: 'text-pink-100',
        brandingColor: 'text-white',
        handleFont: 'font-serif font-bold italic',
        cardBackground: 'bg-white text-[#662D8C]',
        tile1Bg: 'bg-[#662D8C]', tile2Bg: 'bg-[#ED1E79]', tile3Bg: 'bg-white', tile4Bg: 'bg-[#f8bbd0]',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-white/20',
        coverImage: 'bg-gradient-to-br from-[#662D8C] to-[#ED1E79]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent',
        previewBg: '#4c0519'
    },
    {
        id: 'starlight',
        name: 'Starlight',
        category: 'Dark',
        background: '#191970',
        buttonStyle: 'bg-[#FFD700] text-[#191970] font-black',
        textStyle: 'text-[#FFF8DC]',
        brandingColor: 'text-[#FFD700]',
        handleFont: 'font-serif font-black italic text-4xl tracking-tight text-[#FFD700] drop-shadow-[0_0_10px_rgba(255,215,0,0.5)]',
        cardBackground: 'bg-white/5 backdrop-blur-md text-white border border-white/10 font-bold uppercase tracking-widest text-[10px]',
        tile1Bg: 'bg-[#191970]', tile2Bg: 'bg-[#FFD700]', tile3Bg: 'bg-white/10', tile4Bg: 'bg-black',
        brandingBubbleStyle: 'bg-white/10 backdrop-blur-md border border-white/10',
        coverImage: 'bg-gradient-to-br from-[#191970] to-[#FFD700]',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-[#191970]/60 backdrop-blur-xl text-[#FFF8DC] border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-[#FFD700] text-[#191970] rounded-2xl rounded-br-sm shadow-xl px-4 py-2 border border-black/10',
        chatInputStyle: 'bg-white/5 text-[#FFF8DC] border border-white/10 rounded-full focus:outline-none placeholder-[#FFF8DC]/20 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-[#191970] via-[#191970]/80 to-transparent',
        previewBg: '#020617'
    },
];

export const themeCategories = ['Vibrant', 'Minimal', 'Dark', 'Organic', 'Monochrome', 'Gradient', 'Y2K', 'Aesthetic', 'Abstract'];
