export const themes = [
    {
        id: 'liquid-green',
        name: 'Liquid Green',
        category: 'Vibrant',
        background: 'url("https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=2070&auto=format&fit=crop")',
        buttonStyle: 'bg-[#b6ff00] text-black border border-transparent hover:scale-105 transition-transform',
        textStyle: 'text-black',
        handleFont: 'font-serif italic tracking-wide text-[#b6ff00] drop-shadow-[0_1px_2px_rgba(0,0,0,0.8)]',
        cardBackground: 'bg-white/90 backdrop-blur-md text-black font-semibold',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'clean-white',
        name: 'Clean White',
        category: 'Minimal',
        background: '#f4f4f5',
        buttonStyle: 'bg-white text-black border border-gray-200 shadow-sm hover:bg-gray-50 transition-colors',
        textStyle: 'text-black',
        handleFont: 'font-sans font-bold',
        cardBackground: 'bg-white text-black font-medium shadow-sm',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'dark-3d-star',
        name: 'Dark 3D Star',
        category: 'Dark',
        background: 'linear-gradient(to bottom, #181816, #20201c)',
        buttonStyle: 'bg-white/20 text-white backdrop-blur-md border border-white/10 hover:bg-white/30 transition-colors shadow-[0_4px_30px_rgba(0,0,0,0.1)]',
        textStyle: 'text-white',
        handleFont: 'font-sans font-semibold tracking-tight',
        cardBackground: 'bg-white text-black font-semibold',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'light-cloth',
        name: 'Light Cloth',
        category: 'Organic',
        background: 'url("https://images.unsplash.com/photo-1601243765103-68d27fd11c34?q=80&w=1956&auto=format&fit=crop")',
        buttonStyle: 'bg-black/5 text-black border border-black/10 hover:bg-black/10 transition-colors backdrop-blur-sm',
        textStyle: 'text-[#333333]',
        handleFont: 'font-serif italic font-medium',
        cardBackground: 'bg-white text-black font-semibold shadow-sm',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'bw-contrast',
        name: 'B&W Contrast',
        category: 'Monochrome',
        background: 'linear-gradient(to bottom, #d4d4d4, #e5e5e5)',
        buttonStyle: 'bg-white/50 text-black border border-white/40 backdrop-blur-md hover:bg-white/70 transition-colors',
        textStyle: 'text-black',
        handleFont: 'font-serif italic font-medium text-3xl',
        cardBackground: 'bg-white text-black font-semibold',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'minimal-light',
        name: 'Minimal Light',
        category: 'Minimal',
        background: '#FFFFFF',
        buttonStyle: 'bg-black text-white',
        textStyle: 'text-black',
        handleFont: 'font-sans font-bold',
        cardBackground: 'bg-white border border-gray-200',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'minimal-dark',
        name: 'Minimal Dark',
        category: 'Minimal',
        background: '#000000',
        buttonStyle: 'bg-white text-black',
        textStyle: 'text-white',
        handleFont: 'font-sans font-bold',
        cardBackground: 'bg-white text-black',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'soft-sand',
        name: 'Soft Sand',
        category: 'Minimal',
        background: '#F5F5DC',
        buttonStyle: 'bg-[#8B4513] text-white',
        textStyle: 'text-[#5C4033]',
        handleFont: 'font-sans font-medium',
        cardBackground: 'bg-white text-black',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'slate-grey',
        name: 'Slate Grey',
        category: 'Minimal',
        background: '#708090',
        buttonStyle: 'bg-white text-[#708090]',
        textStyle: 'text-white',
        handleFont: 'font-sans font-light tracking-wide',
        cardBackground: 'bg-white text-black',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'pebble',
        name: 'Pebble',
        category: 'Minimal',
        background: '#E0E0E0',
        buttonStyle: 'bg-black text-white',
        textStyle: 'text-gray-800',
        handleFont: 'font-sans font-medium',
        cardBackground: 'bg-white',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'sunset-glow',
        name: 'Sunset Glow',
        category: 'Gradient',
        background: 'linear-gradient(135deg, #FF7E5F, #FEB47B)',
        buttonStyle: 'bg-white/20 text-white backdrop-blur-sm border border-white/30',
        textStyle: 'text-white',
        handleFont: 'font-sans font-bold',
        cardBackground: 'bg-white text-[#FF7E5F]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'ocean-breeze',
        name: 'Ocean Breeze',
        category: 'Gradient',
        background: 'linear-gradient(135deg, #00C9FF, #92FE9D)',
        buttonStyle: 'bg-white text-[#00C9FF] shadow-lg',
        textStyle: 'text-white',
        handleFont: 'font-sans font-bold',
        cardBackground: 'bg-white text-[#00C9FF]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'midnight-purple',
        name: 'Midnight Purple',
        category: 'Gradient',
        background: 'linear-gradient(135deg, #4A00E0, #8E2DE2)',
        buttonStyle: 'bg-transparent text-white border-2 border-white',
        textStyle: 'text-white',
        handleFont: 'font-sans font-bold',
        cardBackground: 'bg-white text-[#4A00E0]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'cherry-blossom',
        name: 'Cherry Blossom',
        category: 'Gradient',
        background: 'linear-gradient(135deg, #FF9A9E, #FECFEF)',
        buttonStyle: 'bg-white/50 text-[#D84380] backdrop-blur-md',
        textStyle: 'text-[#D84380]',
        handleFont: 'font-serif font-bold',
        cardBackground: 'bg-white text-[#D84380]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'neon-city',
        name: 'Neon City',
        category: 'Gradient',
        background: 'linear-gradient(135deg, #0F2027, #203A43, #2C5364)',
        buttonStyle: 'bg-[#00FF87] text-black font-bold border border-[#60EFFF] shadow-[0_0_15px_rgba(0,255,135,0.5)]',
        textStyle: 'text-white',
        handleFont: 'font-mono uppercase tracking-widest',
        cardBackground: 'bg-[#00FF87] text-black',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'cyber-punk',
        name: 'Cyberpunk',
        category: 'Y2K',
        background: '#0D0E15',
        buttonStyle: 'bg-transparent text-[#FCEE0A] border-2 border-[#FCEE0A] shadow-[4px_4px_0_#FCEE0A] hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all',
        textStyle: 'text-[#00FFFF]',
        handleFont: 'font-mono font-bold',
        cardBackground: 'bg-[#FCEE0A] text-black uppercase',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'vaporwave',
        name: 'Vaporwave',
        category: 'Y2K',
        background: 'linear-gradient(180deg, #FF71CE, #01CDFE)',
        buttonStyle: 'bg-[#B967FF] text-white border-[3px] border-white font-bold',
        textStyle: 'text-white text-shadow-sm',
        handleFont: 'font-serif italic font-bold',
        cardBackground: 'bg-white text-[#B967FF]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'brutalism',
        name: 'Brutalism',
        category: 'Aesthetic',
        background: '#D6D6D6',
        buttonStyle: 'bg-black text-white border-4 border-black font-black uppercase hover:bg-white hover:text-black transition-colors',
        textStyle: 'text-black',
        handleFont: 'font-sans font-black uppercase text-4xl',
        cardBackground: 'bg-black text-white uppercase',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'glassmorphism',
        name: 'Glassmorphism',
        category: 'Aesthetic',
        background: 'linear-gradient(45deg, #12c2e9, #c471ed, #f64f59)',
        buttonStyle: 'bg-white/10 text-white backdrop-blur-xl border border-white/20 shadow-[0_8px_32px_0_rgba(31,38,135,0.37)]',
        textStyle: 'text-white',
        handleFont: 'font-sans font-light',
        cardBackground: 'bg-white/20 backdrop-blur-xl text-white',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'pastel-dreams',
        name: 'Pastel Dreams',
        category: 'Aesthetic',
        background: '#FDF6E3',
        buttonStyle: 'bg-[#FFB7B2] text-white shadow-sm',
        textStyle: 'text-[#878681]',
        handleFont: 'font-serif italic',
        cardBackground: 'bg-[#E2F0CB] text-[#555]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'forest',
        name: 'Forest',
        category: 'Organic',
        background: '#2C4C3B',
        buttonStyle: 'bg-[#E8F1E9] text-[#2C4C3B]',
        textStyle: 'text-[#E8F1E9]',
        handleFont: 'font-serif font-bold',
        cardBackground: 'bg-white text-[#2C4C3B]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'clay',
        name: 'Clay',
        category: 'Organic',
        background: '#C49A7E',
        buttonStyle: 'bg-[#5C4033] text-white',
        textStyle: 'text-[#3E2723]',
        handleFont: 'font-sans font-medium',
        cardBackground: 'bg-white text-[#5C4033]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'sage',
        name: 'Sage',
        category: 'Organic',
        background: '#8A9A86',
        buttonStyle: 'bg-white/30 text-white backdrop-blur-sm border border-white/40',
        textStyle: 'text-white',
        handleFont: 'font-sans font-light',
        cardBackground: 'bg-white text-[#8A9A86]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'desert',
        name: 'Desert',
        category: 'Organic',
        background: '#E0B589',
        buttonStyle: 'bg-[#9A6A4E] text-white shadow-md',
        textStyle: 'text-[#5E3A25]',
        handleFont: 'font-serif font-bold uppercase',
        cardBackground: 'bg-[#9A6A4E] text-white',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'moss',
        name: 'Moss',
        category: 'Organic',
        background: '#596C56',
        buttonStyle: 'bg-transparent text-[#D4DFD2] border border-[#D4DFD2]',
        textStyle: 'text-[#D4DFD2]',
        handleFont: 'font-sans font-medium',
        cardBackground: 'bg-[#D4DFD2] text-[#596C56]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'pop-art',
        name: 'Pop Art',
        category: 'Vibrant',
        background: '#FFD700',
        buttonStyle: 'bg-[#FF1493] text-white font-black border-4 border-black shadow-[4px_4px_0_black]',
        textStyle: 'text-black',
        handleFont: 'font-sans font-black uppercase',
        cardBackground: 'bg-white text-black font-black border-2 border-black',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'bubblegum',
        name: 'Bubblegum',
        category: 'Vibrant',
        background: '#FF69B4',
        buttonStyle: 'bg-white text-[#FF69B4] font-bold shadow-lg',
        textStyle: 'text-white',
        handleFont: 'font-sans font-bold',
        cardBackground: 'bg-white text-[#FF69B4]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'citrus',
        name: 'Citrus',
        category: 'Vibrant',
        background: '#FF8C00',
        buttonStyle: 'bg-[#FFFF00] text-black font-bold',
        textStyle: 'text-white',
        handleFont: 'font-sans font-black',
        cardBackground: 'bg-[#FFFF00] text-black',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'royal-blue',
        name: 'Royal',
        category: 'Vibrant',
        background: '#4169E1',
        buttonStyle: 'bg-[#FFD700] text-black font-bold shadow-[0_4px_14px_0_rgba(255,215,0,0.39)]',
        textStyle: 'text-white',
        handleFont: 'font-serif',
        cardBackground: 'bg-white text-[#4169E1]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'hyper-pink',
        name: 'Hyper Pink',
        category: 'Vibrant',
        background: '#FF007F',
        buttonStyle: 'bg-black text-white',
        textStyle: 'text-white',
        handleFont: 'font-mono font-bold',
        cardBackground: 'bg-white text-black',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'grid-paper',
        name: 'Grid Paper',
        category: 'Abstract',
        background: '#f0f0f0 radial-gradient(#d7d7d7 1px, transparent 1px)',
        backgroundSize: '20px 20px',
        buttonStyle: 'bg-white text-blue-600 border border-blue-600 font-mono',
        textStyle: 'text-blue-800',
        handleFont: 'font-mono font-bold',
        cardBackground: 'bg-blue-600 text-white',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'dots',
        name: 'Polka Dots',
        category: 'Abstract',
        background: '#FFC0CB radial-gradient(#FF69B4 2px, transparent 2px)',
        backgroundSize: '15px 15px',
        buttonStyle: 'bg-white text-[#FF69B4] shadow-md',
        textStyle: 'text-[#C71585]',
        handleFont: 'font-sans font-extrabold',
        cardBackground: 'bg-white text-[#C71585]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'checkerboard',
        name: 'Checkerboard',
        category: 'Abstract',
        background: 'conic-gradient(from 90deg at 2px 2px,#0000 90deg,#fff 0) 0 0/20px 20px, #000',
        buttonStyle: 'bg-[#FFD700] text-black font-black uppercase border-2 border-black shadow-[4px_4px_0_black]',
        textStyle: 'text-white bg-black/50 px-4 py-1 rounded inline-block',
        handleFont: 'font-sans font-black uppercase text-white bg-black/50 px-2 py-1',
        cardBackground: 'bg-white text-black',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'waves',
        name: 'Waves',
        category: 'Abstract',
        background: 'repeating-radial-gradient( circle at 0 0, transparent 0, #4ca1af 10px ), repeating-linear-gradient( #2c3e50, #2c3e50 )',
        buttonStyle: 'bg-white/20 text-white backdrop-blur-md border border-white/30',
        textStyle: 'text-white',
        handleFont: 'font-serif italic',
        cardBackground: 'bg-white text-[#2c3e50]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'stripes',
        name: 'Stripes',
        category: 'Abstract',
        background: 'repeating-linear-gradient( 45deg, #606dbc, #606dbc 10px, #465298 10px, #465298 20px )',
        buttonStyle: 'bg-white text-[#465298] shadow-lg font-bold',
        textStyle: 'text-white',
        handleFont: 'font-sans font-black',
        cardBackground: 'bg-white text-[#465298]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'obsidian',
        name: 'Obsidian',
        category: 'Dark',
        background: '#0B0C10',
        buttonStyle: 'bg-[#1F2833] text-[#66FCF1] border border-[#45A29E] hover:bg-[#45A29E] hover:text-black transition-colors',
        textStyle: 'text-[#C5C6C7]',
        handleFont: 'font-mono font-bold text-[#66FCF1]',
        cardBackground: 'bg-[#66FCF1] text-black',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'midnight',
        name: 'Midnight',
        category: 'Dark',
        background: '#121212',
        buttonStyle: 'bg-white/10 text-white border border-white/20 backdrop-blur-md',
        textStyle: 'text-gray-300',
        handleFont: 'font-sans font-medium',
        cardBackground: 'bg-white text-black',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'velvet',
        name: 'Velvet',
        category: 'Dark',
        background: '#350018',
        buttonStyle: 'bg-[#DEA5A4] text-[#350018] font-serif font-bold',
        textStyle: 'text-[#DEA5A4]',
        handleFont: 'font-serif italic text-3xl',
        cardBackground: 'bg-[#DEA5A4] text-[#350018]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'emerald-city',
        name: 'Emerald City',
        category: 'Dark',
        background: '#023020',
        buttonStyle: 'bg-transparent text-[#50C878] border-2 border-[#50C878]',
        textStyle: 'text-[#50C878]',
        handleFont: 'font-sans font-bold',
        cardBackground: 'bg-[#50C878] text-white',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'deep-space',
        name: 'Deep Space',
        category: 'Dark',
        background: 'radial-gradient(circle at center, #1B2735 0%, #090A0F 100%)',
        buttonStyle: 'bg-white/5 text-white backdrop-blur-xl border border-white/10 shadow-[0_0_15px_rgba(255,255,255,0.1)]',
        textStyle: 'text-gray-400',
        handleFont: 'font-mono font-light tracking-[0.2em]',
        cardBackground: 'bg-white text-black',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'luna',
        name: 'Luna',
        category: 'Abstract',
        background: '#F0E6D2',
        buttonStyle: 'bg-[#3C3C3C] text-[#F0E6D2]',
        textStyle: 'text-[#3C3C3C]',
        handleFont: 'font-serif font-medium',
        cardBackground: 'bg-[#3C3C3C] text-white',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'mars',
        name: 'Mars',
        category: 'Abstract',
        background: '#AD3611',
        buttonStyle: 'bg-[#FF8C66] text-[#4A1607] font-bold',
        textStyle: 'text-[#FFD1BF]',
        handleFont: 'font-sans font-black uppercase text-4xl',
        cardBackground: 'bg-white text-[#AD3611]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    },
    {
        id: 'aurora',
        name: 'Aurora',
        category: 'Gradient',
        background: 'linear-gradient(to right, #00c6ff, #0072ff)',
        buttonStyle: 'bg-white/20 backdrop-blur-lg text-white border border-white/50 shadow-lg',
        textStyle: 'text-[#E0FFFF]',
        handleFont: 'font-sans font-light text-2xl',
        cardBackground: 'bg-white text-[#0072ff]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'nebula',
        name: 'Nebula',
        category: 'Gradient',
        background: 'radial-gradient(circle, #662D8C 0%, #ED1E79 100%)',
        buttonStyle: 'bg-white text-[#662D8C] font-bold shadow-xl',
        textStyle: 'text-pink-100',
        handleFont: 'font-serif font-bold italic',
        cardBackground: 'bg-white text-[#662D8C]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-white/80 backdrop-blur-md text-black border border-black/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-black/10 backdrop-blur-md text-black rounded-2xl rounded-br-sm shadow-sm border border-black/5',
        chatInputStyle: 'bg-white/60 text-black border border-black/20 rounded-full focus:outline-none focus:ring-1 focus:ring-black/50 placeholder-black/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-white/90 via-white/50 to-transparent'
    },
    {
        id: 'starlight',
        name: 'Starlight',
        category: 'Dark',
        background: '#191970',
        buttonStyle: 'bg-[#FFD700] text-[#191970] font-black',
        textStyle: 'text-[#FFF8DC]',
        handleFont: 'font-sans font-medium',
        cardBackground: 'bg-[#FFD700] text-[#191970]',
        coverImage: 'bg-gradient-to-br from-gray-800 to-gray-900',
        socialIconStyle: 'bg-white/10 text-white border border-white/20 hover:bg-white/20 transition-colors',
        chatBubbleAIStyle: 'bg-black/60 backdrop-blur-md text-white border border-white/10 rounded-2xl rounded-bl-sm shadow-sm',
        chatBubbleUserStyle: 'bg-white/20 backdrop-blur-md text-white rounded-2xl rounded-br-sm shadow-sm border border-white/10',
        chatInputStyle: 'bg-black/40 text-white border border-white/20 rounded-full focus:outline-none focus:ring-1 focus:ring-white/50 placeholder-white/50 backdrop-blur-md',
        chatInputContainerStyle: 'bg-gradient-to-t from-black/80 via-black/50 to-transparent'
    }
];

export const themeCategories = ['Vibrant', 'Minimal', 'Dark', 'Organic', 'Monochrome', 'Gradient', 'Y2K', 'Aesthetic', 'Abstract'];
